image: node:latest

include:
  - template: Code-Quality.gitlab-ci.yml

cache:
  key: the-one-and-only-cache-key
  paths:
    - .npm
    - node_modules

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - test
#  - deploy  TODO uncomment this

analyse:
  stage: test
  script:
    - npm run analyse
  except:
    - master

lint:
  stage: test
  script:
    - npm run analyse
  except:
    - master

deploy:
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build
    # clone deploy repo and throw away all content but .git/ and CNAME
    - git clone https://github.com/${GITLAB_USER_LOGIN}/${DEPLOY_REPO}.git
    - mv ${DEPLOY_REPO} ${DEPLOY_REPO}-old
    - mkdir ${DEPLOY_REPO}
    - mv -t ${DEPLOY_REPO} ${DEPLOY_REPO}-old/.git ${DEPLOY_REPO}-old/CNAME
    # add newly built content
    - cp -rf public/* ${DEPLOY_REPO}
    - cd ${DEPLOY_REPO}
    - git add .
    # commit and push
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email ${GITLAB_USER_EMAIL}
    - git commit -m ${CI_COMMIT_SHORT_SHA}
    - git push https://${GITLAB_USER_LOGIN}:${DEPLOY_TOKEN}@github.com/${GITLAB_USER_LOGIN}/${DEPLOY_REPO}.git HEAD
  only:
    - master
